print('Hello, World!')
print('Today is the fourth of december, and i am hungry')
print('I am in search of a new thing to do, next year i will start college')
print('i do not know what to write here, i wanna start an ADS degree at FATEC, but i am not so sure if i will be able to stay at my current job')
print('My Spotify retrospective looks way different than what i thought it would look like')